export const RELOAD_TASK_LIST = "RELOAD_TASK_LIST";
export const FETCH_SELECTED_TASK = "FETCH_SELECTED_TASK";
export const SET_IS_EDIT = "SET_IS_EDIT";
export const SET_TASK_FORM_VISIBLITY = "SET_TASK_FORM_VISIBLITY";
